./do ReadWriteFile.txt
./do SplitFile.txt
./do ExpandFile.txt
./do DifferentCommands
./do Distinct
./do FilterByDifferentCompareOperators
./do GroupBy
./do GroupByOneColumn
./do JoinTable
./do JoinTableFullStreaming
./do SelectColumn
./do SelectColumnRow
./do SelectRow 
./do SelectUnmatch
